cc_library(
    name = "bellman_ford",
    srcs = glob([
        "bellman_ford.hpp",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "mod",
    srcs = glob([
        "mod.hpp",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "prime_number",
    srcs = glob([
        "prime_number.hpp",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "union_find",
    srcs = glob([
        "union_find.hpp",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "pow",
    srcs = glob([
        "pow.hpp",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "kruscal",
    srcs = glob([
        "kruscal.hpp",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "combination",
    srcs = glob([
        "combination.hpp",
    ]),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "segment_tree",
    srcs = glob([
        "segment_tree.hpp",
    ]),
    visibility = ["//visibility:public"],
)